package com.example.calculator

class Countries {
    companion object {
        val CURRENCY_CODES_LIST = listOf(
            CurrencyAndCountry("Afghanistan", "AFN"),
            CurrencyAndCountry("Albania", "ALL"),
            CurrencyAndCountry("Angola", "AOA"),
            CurrencyAndCountry("Argentina", "ARS"),
            CurrencyAndCountry("Armenia", "AMD"),
            CurrencyAndCountry("Aruba", "AWD"),
            CurrencyAndCountry("Australia", "AUD"),
            CurrencyAndCountry("Azerbaijan", "AZN"),
            CurrencyAndCountry("Bahamas", "BSD"),
            CurrencyAndCountry("Bahrain", "BHD"),
            CurrencyAndCountry("Bangladesh", "BDT"),
            CurrencyAndCountry("Barbados", "BBD"),
            CurrencyAndCountry("Belarus","BYN"),
            CurrencyAndCountry("Belize","BZD"),
            CurrencyAndCountry("Bermuda","BMD"),
            CurrencyAndCountry("Bhutan","BTN"),
            CurrencyAndCountry("Bolivia","BOB"),
            CurrencyAndCountry("Bosnia And Herzegovina","BAM"),
            CurrencyAndCountry("Botswana","BWP"),
            CurrencyAndCountry("Brazil", "BRL"),
            CurrencyAndCountry("Brunei","BND"),
            CurrencyAndCountry("Bulgaria", "BGN"),
            CurrencyAndCountry("Burundi","BIF"),
            CurrencyAndCountry("Cabo Vrede","CVE"),
            CurrencyAndCountry("Cambodia","KHR"),
            CurrencyAndCountry("Canada", "CAD"),
            CurrencyAndCountry("Cayman Islands","KYD"),
            CurrencyAndCountry("Chile","CLF"),
            CurrencyAndCountry("Chile","CLP"),
            CurrencyAndCountry("China", "CNY"),
            CurrencyAndCountry("Colombia","COP"),
            CurrencyAndCountry("Colombia","COU"),
            CurrencyAndCountry("Comoros","KMF"),
            CurrencyAndCountry("DR of The Congo","CDF"),
            CurrencyAndCountry("Costa Rica","CRC"),
            CurrencyAndCountry("Czech Republic", "CZK"),
            CurrencyAndCountry("Denmark", "DKK"),
            CurrencyAndCountry("European Union", "EUR"),
            CurrencyAndCountry("Great Britain", "GBP"),
            CurrencyAndCountry("Hong Kong", "HKD"),
            CurrencyAndCountry("Hungary", "HUF"),
            CurrencyAndCountry("Iceland", "ISK"),
            CurrencyAndCountry("India", "INR"),
            CurrencyAndCountry("Indonesia", "IDR"),
            CurrencyAndCountry("Israel", "ILS"),
            CurrencyAndCountry("Japan", "JPY"),
            CurrencyAndCountry("Korea", "KRW"),
            CurrencyAndCountry("Malaysia", "MYR"),
            CurrencyAndCountry("Mexico", "MXN"),
            CurrencyAndCountry("New Zealand", "NZD"),
            CurrencyAndCountry("Norway", "NOK"),
            CurrencyAndCountry("Philippines", "PHP"),
            CurrencyAndCountry("Poland", "PLN"),
            CurrencyAndCountry("Romania", "RON"),
            CurrencyAndCountry("Russia", "RUB"),
            CurrencyAndCountry("Singapore", "SGD"),
            CurrencyAndCountry("South Africa", "ZAR"),
            CurrencyAndCountry("Sweden", "SEK"),
            CurrencyAndCountry("Switzerland", "CHF"),
            CurrencyAndCountry("Thailand", "THB"),
            CurrencyAndCountry("Turkey", "TRY"),
            CurrencyAndCountry("United States", "USD"),
        )
    }
}